# Generated by Django 3.0.3 on 2020-06-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_image',
            field=models.ImageField(default=None, upload_to='original_images'),
        ),
        migrations.CreateModel(
            name='ImageAttentionDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_image', models.ImageField(default=None, upload_to='attention_images')),
                ('attention_word', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_recognition.Image')),
            ],
        ),
    ]
