# Generated by Django 3.0.3 on 2020-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition', '0003_image_description_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='model_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
